### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by jzkitchen** [mirror-media/plate-vue-dfp#9]
How can I find out the information to fill in sectionId, aduid ? I am confused about all these options...

**Comment by chiangkeith** [comment]
hi @jzkitchen , will update the doc and talk about the usage in days.

**Comment by jzkitchen** [comment]
thx a lot. I spend few days to read articles about implementation of DFP in Vue. Your code will be very helpful!

**Comment by chiangkeith** [comment]
Hello @jzkitchen ,
Regarding `sectionid`, you can set any value of string you want it to be. It's a reference for `VueDfpProvider` to know which setting you're about to use in the array `adunits`:

```javascript
adunits: {
  'section-id': {
    'POSITION1': { 'aduid': 'ADUNIT-ID-1', ... },
    'POSITION2': { ... }
  },
  'section-id2': { ... }
}
```
 
And `aduid` is the `unit code` that should be offered as soon as you build any ad unit on DFP system. (checkout [ad unit](https://support.google.com/dfp_premium/answer/177203?hl=en))
